#theme: jekyll-theme-minimal
# remote_theme: mmistakes/minimal-mistakes
# remote_theme: poole/lanyon
#remote_theme: "alshedivat/al-folio"
# minimal_mistakes_skin: "air"

#remote_theme: poole/hyde
title: Ashraf Ahmed's Portfolio
description: A jekyll themed portfolio site that contains information about my coding experience, background and relevant professional information.

# minima:
#     skin: dark

# header_pages:
#     - about.md
#     - portfolio.md
#     - projects.md
theme: jekyll-theme-minimal
logo: https://avatars3.githubusercontent.com/u/16357832?s=400&u=236b9145f6e5111e1c97495731168bf8117d535a&v=4