#theme: jekyll-theme-minimal
# remote_theme: mmistakes/minimal-mistakes
# remote_theme: poole/lanyon
#remote_theme: "alshedivat/al-folio"
# minimal_mistakes_skin: "air"

#remote_theme: poole/hyde
title: About Me
description: Technology Entrepreneur, Software Architect Freelancer, Student of Statistics, Neuroscience, and Machine Learning.

# minima:
#     skin: dark

# header_pages:
#     - about.md
#     - portfolio.md
#     - projects.md
theme: jekyll-theme-minimal
logo: https://avatars3.githubusercontent.com/u/16357832?s=400&u=236b9145f6e5111e1c97495731168bf8117d535a&v=4